
Date=2025-11-12
PDC-1="Aluminum-Polished", "Copper-Oxidized", 1.50, 1.1, 0.2
PDC-2="Aluminum-Polished", "Aluminum-Anodized", 2.50, 2.120, 0.20
PDC-3="Copper-Polished", "Steel-Oxidized", 3.50, 2.50, 0.25