# S_Date is the starting date for analysis
S_Date=2026-01-01
# E_Date is the end date to stop data analysis
E_Date=2026-01-30

# Location is the area/region of interest [see sim.conf for all listed regions], leave blank
# to process all locations
Location=

# PDC is paranolic dish configuration [See collector classes]
PDC-1=Aluminum-Polished, Selective, SilicaAerogel, 5.0, 0.71, 0.2
PDC-2=Steel-Polished, Selective, SilicaAerogel, 2.50, 2.120, 0.20
PDC-3=Aluminum-Polished, BlackPaint, SilicaAerogel, 3.50, 2.50, 0.25
PDC-4=Copper-Polished, Selective, SilicaAerogel, 3.50, 2.50, 0.25