S_Date=2026-01-01
E_Date=2026-01-05

Location=Abuja

PDC-1=Aluminum-Polished, Copper-Oxidized, SilicaAerogel, 5.0, 2.1, 0.2
# PDC-2=Aluminum-Polished, Aluminum-Anodized, SilicaAerogel, 2.50, 2.120, 0.20
# PDC-3=Copper-Polished, Steel-Oxidized, SilicaAerogel, 3.50, 2.50, 0.25