# Simulation Configuration File
# Format: LocationX=street_number, street, city, province, country

Abuja=Ahmadu Bello Wy, Garki 2, Abuja 900103, Federal Capital Territory, Nigeria
Kano=Airport Rd, Gwagwarwa, Kano 700211, Kano, Nigeria
Sokoto=Filin Jirgi, Sokoto 840283, Sokoto, Nigeria
Lagos=Ikotun, Lagos 102213, Lagos, Nigeria
Alberta=34 Hidden Hills Terrace NW, Calgary, AB T3A 6E1
Aachen=19 Romerstrasse 52064 Aachen, NRW, Germany